export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  // —— 病害转修复方案闭环 ——
  DAMAGE_NOT_FOUND: "DAMAGE_NOT_FOUND",
  DAMAGE_LOCKED: "DAMAGE_LOCKED",
  DAMAGE_CLOSED: "DAMAGE_CLOSED",
  ACTIVE_PLAN_EXISTS: "ACTIVE_PLAN_EXISTS",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  PLAN_STATUS_CONFLICT: "PLAN_STATUS_CONFLICT",
  CONCURRENT_TRANSFER: "CONCURRENT_TRANSFER",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
